PROJECT_NAME: odl

# database credentials for ODL database. Do not fill out POSTGRES_USER and _PW
# Will be added by those of your .env file
SERVER_CONFIGS:
  ODL_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: techniek
    POSTGRES_SCHEMA: datamanagement

  # database credentials for storing the data. _USER and _PW will be added from .env
  DATA_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: data
    POSTGRES_SCHEMA: odl

  # database credentials for xtracting the data. _USER and _PW will be added from .env
  FOREIGN_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: data
    POSTGRES_SCHEMA: odl

# select server to use as POSTGRES_HOST
HOST: datawarehouse_dev

# Optionally set major and minor versions
UPDATE_MAJOR_VERSION: no
UPDATE_MINOR_VERSION: yes
INITIAL_VERSION: 0.3.0

ROOT_DIR: /data/arnoldreinders/apps/odl/root
WORK_DIR: /data/arnoldreinders/apps/odl/work

# mandatory sub directories in WORK_DIR
SUBDIRS:
  - data
  - docs
  - done
  - logs
  - schemas
  - sql
  - todo

# Data suppliers: translated into sub directories for each SUBDIRS in WORK_DIR
SUPPLIERS:
  - odl

DOC: logic-model.md
SQL: logic-model.sql

# tables and schema definition files, each table has a corresponding definition file
TABLES:
  odl_rapportageperiodes: {from: odl_rapportageperiodes.csv}
  bronbestand_attribuutmeta: {from: bronbestand_attribuutmeta.csv}
  bronbestand_attribuutextra: {from: bronbestand_attribuutextra.csv}
  bronbestand_bestandmeta: {from: bronbestand_bestandmeta.csv}
  bronbestand_datakwaliteit: {from: bronbestand_datakwaliteit.csv}
  bronbestand_datakwaliteitcodes: {from: bronbestand_datakwaliteitcodes.csv}
  bronbestand_levering: {from: bronbestand_levering.csv}

# list of columns to show in documentation, empty list means show all columns
COLUMNS: []

# Beginning and end of time
BEGINNING_OF_WORLD: 1970-01-01 00:00:00
END_OF_WORLD: 9999-12-31 23:59:59