PROJECT_NAME: odl

# database credentials for ODL database. Do not fill out POSTGRES_USER and _PW
# Will be added by those of your .env file
SERVER_CONFIGS:
  ODL_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: techniek
    POSTGRES_SCHEMA: datamanagement

  # database credentials for storing the data. _USER and _PW will be added from .env
  DATA_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: data
    POSTGRES_SCHEMA: odl

  # database credentials for xtracting the data. _USER and _PW will be added from .env
  FOREIGN_SERVER_CONFIG:
    POSTGRES_PORT: 5432
    POSTGRES_DB: data
    POSTGRES_SCHEMA: odl

# select server to use as POSTGRES_HOST
HOST: datawarehouse_dev

ROOT_DIR: /data/arnoldreinders/apps/odl/root
WORK_DIR: /data/arnoldreinders/apps/odl/work

# mandatory sub directories in WORK_DIR
SUBDIRS:
  - data
  - docs
  - done
  - logs
  - schemas
  - sql
  - todo

# Data suppliers: translated into sub directories for each SUBDIRS in WORK_DIR
SUPPLIERS:
  - odl

DOC: logic-model.md
SQL: logic-model.sql

UPDATE_MAJOR_VERSION: no
UPDATE_MINOR_VERSION: no

# tables and schema definition files, each table has a corresponding definition file
TABLES:
  odl_rapportageperiodes: {from: odl_rapportageperiodes.csv}
  bronbestand_attribuut_meta: {from: bronbestand_attribuut_meta.csv}
  bronbestand_attribuut_extra: {from: bronbestand_attribuut_extra.csv}
  bronbestand_bestand_meta: {from: bronbestand_bestand_meta.csv}
  bronbestand_datakwaliteit_feit: {from: bronbestand_datakwaliteit_feit.csv}
  bronbestand_datakwaliteit_codes: {from: bronbestand_datakwaliteit_codes.csv}
  bronbestand_levering_feit: {from: bronbestand_levering_feit.csv}

# list of columns to show in documentation, empty list means show all columns
COLUMNS: []

# Beginning and end of time
BEGINNING_OF_WORLD: 1970-01-01 00:00:00
END_OF_WORLD: 9999-12-31 23:59:59